services:
  postgres_test:
    image: postgres:alpine
    env_file:
      - './.env.test'
    environment:
      POSTGRES_USER: 'test-ppm-requests'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'test-ppm-requests'
    ports:
      - 5432:5432
    networks:
      - test-network
    restart: 'no'

  node_test:
    depends_on: [postgres_test]
    build:
      context: .
      dockerfile: test.Dockerfile
      network: host
    networks:
      - test-network
    volumes:
      - ./src:./src
    restart: 'no'
    command: sh ./tests.sh
    links:
      - postgres_test

networks:
  test-network:
    driver: bridge