services:
  postgres_test:
    image: postgres:alpine
    env_file:
      - './.env.test'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - test-network
    restart: 'no'

  node_test:
    depends_on: [postgres_test]
    env_file:
      - './.env.test'
    build:
      context: .
      dockerfile: test.Dockerfile
      network: host
    networks:
      - test-network
    volumes:
      - ./src:/src
    restart: 'no'

networks:
  test-network:
    driver: bridge